name: Python application

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7.9, 3.8.5]
        os: ["ubuntu-latest"]

    runs-on: "${{ matrix.os }}"
    
    name: Python version ${{ matrix.python-version }} 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
         activate-conda: true
    - run: conda --version
    - run: conda install python=${{matrix.python-version}}

    - name: Install dependencies, Gfortran and Project
      run: |
         conda config --add channels conda-forge
         conda config --set channel_priority strict
         conda install -c conda-forge --file requirements.txt
         conda install scipy
         conda install pip
         
         pip install .
         echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

         sudo apt-get update
         sudo apt-get install gfortran
         cd drivers
         make

    - name: pytests
      shell: bash
      run: |
         i-pi-tests -t all
